import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { optimize } from 'svgo';

import { iconDefinitions } from '../metadata/icons';
import type { IconCategory, IconManifest, IconMetadata } from '../src/types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, '..');
const rawDir = path.join(packageRoot, 'icons', 'raw');
const optimizedDir = path.join(packageRoot, 'icons', 'optimized');
const generatedDir = path.join(packageRoot, 'generated');

const REQUIRED_ROOT_TOKENS = [
  'viewBox="0 0 24 24"',
  'fill="none"',
  'stroke="currentColor"',
  'stroke-width="1.75"',
  'stroke-linecap="round"',
  'stroke-linejoin="round"',
] as const;

const toComponentName = (iconName: string): string =>
  `${iconName
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')}Icon`;

const validateSvgContract = (iconName: string, svg: string): void => {
  const rootTag = svg.match(/<svg\b[^>]*>/)?.[0];
  if (!rootTag) {
    throw new Error(`Icon "${iconName}" is missing an <svg> root element.`);
  }

  for (const token of REQUIRED_ROOT_TOKENS) {
    if (!rootTag.includes(token)) {
      throw new Error(`Icon "${iconName}" must include ${token} in the root <svg> tag.`);
    }
  }
};

const generate = async (): Promise<void> => {
  const rawFiles = (await fs.readdir(rawDir)).filter((file) => file.endsWith('.svg')).sort();
  const definedNames = Object.keys(iconDefinitions).sort();
  const rawNames = rawFiles.map((file) => file.replace(/\.svg$/, '')).sort();

  const missing = definedNames.filter((name) => !rawNames.includes(name));
  const unexpected = rawNames.filter((name) => !definedNames.includes(name));

  if (missing.length > 0 || unexpected.length > 0) {
    const issues = [
      missing.length > 0 ? `Missing SVG files: ${missing.join(', ')}` : null,
      unexpected.length > 0 ? `Unexpected SVG files: ${unexpected.join(', ')}` : null,
    ]
      .filter(Boolean)
      .join('\n');

    throw new Error(issues);
  }

  await fs.mkdir(optimizedDir, { recursive: true });
  await fs.mkdir(generatedDir, { recursive: true });

  const metadata: Array<IconMetadata & { name: string }> = [];

  for (const fileName of rawFiles) {
    const name = fileName.replace(/\.svg$/, '');
    const definition = iconDefinitions[name as keyof typeof iconDefinitions];

    if (!definition) {
      throw new Error(`Icon definition not found for "${name}".`);
    }

    const rawSvg = await fs.readFile(path.join(rawDir, fileName), 'utf8');
    validateSvgContract(name, rawSvg);

    const optimized = optimize(rawSvg, {
      path: fileName,
      multipass: true,
      plugins: [
        {
          name: 'preset-default',
          params: {
            overrides: {
              cleanupIds: false,
              removeViewBox: false,
            },
          },
        },
        'sortAttrs',
        'removeDimensions',
      ],
    }).data.trim();

    await fs.writeFile(path.join(optimizedDir, fileName), `${optimized}\n`, 'utf8');

    metadata.push({
      name,
      componentName: toComponentName(name),
      title: definition.title,
      category: definition.category,
      tags: definition.tags,
      terms: definition.terms,
      rawPath: `icons/raw/${fileName}`,
      optimizedPath: `icons/optimized/${fileName}`,
      svg: optimized,
    });
  }

  const categories = metadata.reduce<Partial<Record<IconCategory, number>>>((acc, icon) => {
    acc[icon.category] = (acc[icon.category] ?? 0) + 1;
    return acc;
  }, {});

  const manifest: IconManifest = {
    packageName: '@thinicons/core',
    generatedAt: new Date().toISOString(),
    total: metadata.length,
    categories,
    icons: metadata,
  };

  const iconNames = metadata.map((entry) => entry.name);

  const generatedTsSource = `/* eslint-disable */\n/* This file is auto-generated by scripts/optimize-icons.ts */\n\nimport type { IconManifest, IconMetadata } from '../src/types';\n\nexport const iconNames = ${JSON.stringify(iconNames, null, 2)} as const;\nexport type IconName = (typeof iconNames)[number];\n\nexport const iconsMetadata: ReadonlyArray<IconMetadata & { name: IconName }> = ${JSON.stringify(metadata, null, 2)};\n\nexport const iconMetadataMap: Readonly<Record<IconName, IconMetadata & { name: IconName }>> =\n  Object.fromEntries(iconsMetadata.map((icon) => [icon.name, icon])) as Record<\n    IconName,\n    IconMetadata & { name: IconName }\n  >;\n\nexport const iconManifest: Readonly<IconManifest> = ${JSON.stringify(manifest, null, 2)};\n`;

  await fs.writeFile(path.join(generatedDir, 'icons.ts'), generatedTsSource, 'utf8');
  await fs.writeFile(path.join(generatedDir, 'icons.json'), JSON.stringify(metadata, null, 2), 'utf8');
  await fs.writeFile(path.join(generatedDir, 'icon-manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');

  console.log(`Generated ${metadata.length} optimized icons and manifest data.`);
};

generate().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
