import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const ICONS_DIR = path.join(ROOT, 'icons');
const DIST_DIR = path.join(ROOT, 'dist');
const RUNTIME_SRC = path.join(ROOT, 'src', 'iconestia.js');
const GLOBAL_RUNTIME_OUT = path.join(DIST_DIR, 'iconestia.global.js');

function extractViewBox(svg) {
  const m = svg.match(/viewBox\s*=\s*"([^"]+)"/i);
  return m?.[1] || '0 0 24 24';
}

function extractRootAttributes(svg) {
  const m = svg.match(/<svg([^>]*)>/i);
  if (!m?.[1]) return '';

  const attrs = [];
  const attrRegex = /([a-zA-Z_:][\w:.-]*)\s*=\s*"([^"]*)"/g;
  const blocked = new Set(['width', 'height', 'viewBox', 'xmlns', 'xmlns:xlink']);
  let match = attrRegex.exec(m[1]);

  while (match) {
    const name = match[1];
    if (!blocked.has(name)) {
      attrs.push(`${name}="${match[2]}"`);
    }
    match = attrRegex.exec(m[1]);
  }

  return attrs.join(' ');
}

function extractBody(svg) {
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
  return m?.[1]?.trim() || '';
}

function extractNormalizedBody(svg) {
  const body = extractBody(svg);
  if (!body) return '';

  const rootAttrs = extractRootAttributes(svg);
  if (!rootAttrs) return body;
  return `<g ${rootAttrs}>${body}</g>`;
}

async function collectIcons() {
  let files = [];
  try {
    files = await fs.readdir(ICONS_DIR);
  } catch {
    return [];
  }

  const icons = [];
  for (const file of files) {
    if (!file.endsWith('.svg')) continue;

    const name = path.basename(file, '.svg');
    const content = await fs.readFile(path.join(ICONS_DIR, file), 'utf8');
    const body = extractNormalizedBody(content);

    if (!body) continue;

    icons.push({
      name,
      viewBox: extractViewBox(content),
      body,
    });
  }

  return icons;
}

function buildSprite(icons) {
  const symbols = icons
    .map(
      (icon) =>
        `<symbol id="icon-${icon.name}" viewBox="${icon.viewBox}">${icon.body}</symbol>`,
    )
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden"><defs>${symbols}</defs></svg>`;
}

function toGlobalRuntime(source) {
  const runtimeBody = source.replace(/^export\s+/gm, '').trimEnd();

  return `/* Auto-generated by scripts/build-icons.mjs. Do not edit directly. */
(function (global) {
${runtimeBody}

  global.Iconestia = {
    setExternalSprite,
    registerIcons,
    addIconFromSvg,
    loadIconsFromUrl,
    setupIconestia,
    IconestiaIcon,
    defineIconElement
  };
})(window);
`;
}

async function buildGlobalRuntime() {
  const source = await fs.readFile(RUNTIME_SRC, 'utf8');
  const globalRuntime = toGlobalRuntime(source);
  await fs.writeFile(GLOBAL_RUNTIME_OUT, globalRuntime, 'utf8');
}

async function main() {
  const icons = await collectIcons();

  await fs.mkdir(DIST_DIR, { recursive: true });
  await fs.writeFile(path.join(DIST_DIR, 'sprite.svg'), buildSprite(icons), 'utf8');

  const manifest = Object.fromEntries(
    icons.map((icon) => [
      icon.name,
      {
        viewBox: icon.viewBox,
        body: icon.body,
      },
    ]),
  );

  await fs.writeFile(
    path.join(DIST_DIR, 'icons.json'),
    JSON.stringify(manifest, null, 2),
    'utf8',
  );

  await buildGlobalRuntime();

  console.log(`Built ${icons.length} icon(s) plus runtime assets into dist/.`);
}

main();
